title: Product

files: true
  sortable: true
  fields:
    imagealt:
      label: Alt text
      type: text
    formaat:
      label: Formaat
      type: text
      
pages: true
  sortable: true

options:
  template: true

fields:
  title:
    label: Page title (H1)
    type: text
    width: 1/2

  productmainimage:
    label: Hoofdafbeelding
    type: image    
    width: 1/2

  slides:
      label: Slider
      type: structure
      fields:
        slide:
          label: Slide
          type: image
        caption:
          label: Bijschrift
          type: text
    
  producttitle:
    label: Product titel
    type:  text
    width: 1/2

  text:
    label: Text
    type:  wysiwyg

  pictures:
    label: Gallery
    type: gallery
    aspectRatio: 4:3